<?php

// <auto-generated/>
// Flame Core File

use Views\Files\FlameFile;

$__generated___FlameViewFile_____ = new FlameFile(__FILE__);

FlameView('::init-file-flameEngine::')->fileSetConfigFlameFile($__generated___FlameViewFile_____);

?>